### ISSUE TITLE
Run demo with a error in mac os 13.4.1 (22F82)

### ISSUE THREAD

**Issue by lanch** [BabitMF/bmf#56]
hi， I run the demo in my mac, but got the error, how to fix the error?

 demo % python broadcaster/broadcaster.py
Traceback (most recent call last):
  File "/Users/weiliang/Develop/bmf/bmf/demo/broadcaster/broadcaster.py", line 7, in <module>
    import bmf
  File "/Users/weiliang/.pyenv/versions/3.9.18/lib/python3.9/site-packages/bmf/__init__.py", line 3, in <module>
    from bmf.python_sdk.module_functor import make_sync_func
  File "/Users/weiliang/.pyenv/versions/3.9.18/lib/python3.9/site-packages/bmf/python_sdk/__init__.py", line 1, in <module>
    from .module_functor import make_sync_func, ProcessDone
  File "/Users/weiliang/.pyenv/versions/3.9.18/lib/python3.9/site-packages/bmf/python_sdk/module_functor.py", line 1, in <module>
    import bmf.lib._hmp
ImportError: dlopen(/Users/weiliang/.pyenv/versions/3.9.18/lib/python3.9/site-packages/bmf/lib/_hmp.cpython-39-darwin.so, 0x0002): Library not loaded: @executable_path/../../../../Python
  Referenced from: <A7C35633-CEDB-33E7-9D07-2098CB1A21E1> /Users/weiliang/.pyenv/versions/3.9.18/lib/python3.9/site-packages/bmf/lib/_hmp.cpython-39-darwin.so
  Reason: tried: '/Users/weiliang/Python' (no such file), '/usr/local/lib/Python' (no such file), '/usr/lib/Python' (no such file, not in dyld cache)

**Comment by taoboyang** [comment]
Hello, there, sry for the problem. In fact, the BMF framework is currently ready for Mac infrastructure. There may be problems with some environment monitoring configurations. We are rectifying them and accelerating support. Thank you for your patience.

**Comment by taoboyang** [comment]
Hello, I want to know how do you install BMF, through pip install BabitMF? I did a local test here. I installed python3.9 using homebrew, and the problems you exposed did not occur. Would you please provide more detailed environment information?

**Comment by lanch** [comment]
> Hello, I want to know how do you install BMF, through pip install BabitMF? I did a local test here. I installed python3.9 using homebrew, and the problems you exposed did not occur. Would you please provide more detailed environment information?

I use pyenv to install the python 3.9, and pip install BabitMF

**Comment by IdiosyncraticDragon** [comment]
I had installed python 3.10 through conda, and met the same problem. It seems like the default python path is fixed to '/Users/[USERNAME]/Python'.

**Comment by JackLau1222** [comment]
> > Hello, I want to know how do you install BMF, through pip install BabitMF? I did a local test here. I installed python3.9 using homebrew, and the problems you exposed did not occur. Would you please provide more detailed environment information?
> 
> I use pyenv to install the python 3.9, and pip install BabitMF

Please ensure there is no conflict between your local python and virtual environment python. 
May you try use this command`python3.9` rather than `python`?

**Comment by wtqn0206** [comment]
I encountered a "Segmentation fault: 11" when running the code with import bmf. My environment is a 2.3 GHz dual-core Intel Core i5, macOS 13.6.9 (22G830), and I'm using Python 3.7 with Conda. Additionally, I also tried using Python 3.9, but I still get the same "Segmentation fault: 11" error.
